'use client';
import React, { useState, useEffect } from 'react';
import './globals.css';
import Footer from '@app/components/Layout/Footer';
import Header from '@app/components/Layout/Header';

/**
 * Using force dynamic so changes in business assets (e.g. services) are immediately reflected.
 * If you prefer having it reflected only after redeploy (not recommended) please remove it
 * **/
export const revalidate = 0;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isScrolled, setIsScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      const scrollTop = window.scrollY;
      setIsScrolled(scrollTop > 0);  
    };

    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  });

  const headerStyle = isScrolled
  ? {
      position: 'fixed',
      top: 0,
      left: 0,
      right: 0,
      backgroundColor: 'white',
      boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
      zIndex: 1000,
    }
  : {};

  const mainStyle = isScrolled
  ? {
      paddingTop: '64px', // Adjust the padding based on your header height
    }
  : {};

  return (
    <html lang="en">
      <head>
        <title>Harns Lab</title>
        <meta
          name="description"
          content="Generated by create next app with Wix Education integration"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href='/images/harnsLogo.png' />
      </head>
      <body className="text-blue-site bg-white">
        <>
        <div style={headerStyle}>
        <Header/> 
        </div>  
          <main style={mainStyle} className="bg-white min-h-[600px]">{children}</main>
          <div className="mt-10 sm:mt-20">
            <Footer />
          </div>
        </>
      </body>
    </html>
  );
}
